#!/bin/bash
#  configure_environment_variables
#  Usage:
#    $ bash configure_environment_variables adorable-creature-1234567890
#      or
#    $ chmod +x configure_environment_variables
#    $ ./configure_environment_variables adorable-creature-1234567890

export PATH=$PATH:~/bin
export CONFIG_URI="https://raw.githubusercontent.com/kubeflow/manifests/v1.0-branch/kfdef/kfctl_aws.v1.0.1.yaml"
export AWS_CLUSTER_NAME=$1  # Example: "adorable-creature-1234567890"
export KF_NAME=${AWS_CLUSTER_NAME}
export BASE_DIR=~/kubeflow/
export KF_DIR=${BASE_DIR}/${KF_NAME}
